"""core schema

Revision ID: 9e1282b09052
Revises:
Create Date: 2026-09-26 03:01:23.681024

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '9e1282b09052'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_category'), 'concepts', ['category'], unique=False)
    op.create_index(op.f('ix_concepts_concept_id'), 'concepts', ['concept_id'], unique=True)
    op.create_index(op.f('ix_concepts_domain'), 'concepts', ['domain'], unique=False)
    op.create_index('ix_concepts_domain_category', 'concepts', ['domain', 'category'], unique=False)
    op.create_table('id_counters',
    sa.Column('prefix', sa.String(length=32), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('prefix')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=False),
    sa.Column('version_or_commit', sa.String(length=128), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.String(length=32), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('commercial_use_status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_table('deduplication_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_a', sa.String(length=64), nullable=False),
    sa.Column('candidate_b', sa.String(length=64), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_a'], ['concepts.concept_id'], ),
    sa.ForeignKeyConstraint(['candidate_b'], ['concepts.concept_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deduplication_candidates_candidate_a'), 'deduplication_candidates', ['candidate_a'], unique=False)
    op.create_index(op.f('ix_deduplication_candidates_candidate_b'), 'deduplication_candidates', ['candidate_b'], unique=False)
    op.create_index(op.f('ix_deduplication_candidates_status'), 'deduplication_candidates', ['status'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.String(length=256), nullable=False),
    sa.Column('concept_id', sa.String(length=64), nullable=True),
    sa.Column('original_payload', sa.JSON(), nullable=False),
    sa.Column('source_version', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('ingestion_timestamp', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.concept_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_records_concept_id'), 'source_records', ['concept_id'], unique=False)
    op.create_index(op.f('ix_source_records_source_id'), 'source_records', ['source_id'], unique=False)
    op.create_table('concept_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('script', sa.String(length=32), nullable=True),
    sa.Column('name_type', sa.String(length=24), nullable=False),
    sa.Column('source_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.concept_id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_names_concept_id'), 'concept_names', ['concept_id'], unique=False)
    op.create_index('ix_concept_names_concept_id_name_type', 'concept_names', ['concept_id', 'name_type'], unique=False)
    op.create_index('ix_concept_names_normalized_name', 'concept_names', ['normalized_name'], unique=False)
    op.create_table('concept_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id_a', sa.String(length=64), nullable=False),
    sa.Column('concept_id_b', sa.String(length=64), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_record_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id_a'], ['concepts.concept_id'], ),
    sa.ForeignKeyConstraint(['concept_id_b'], ['concepts.concept_id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_concept_relationships_a_b', 'concept_relationships', ['concept_id_a', 'concept_id_b'], unique=False)
    op.create_index(op.f('ix_concept_relationships_concept_id_a'), 'concept_relationships', ['concept_id_a'], unique=False)
    op.create_index(op.f('ix_concept_relationships_concept_id_b'), 'concept_relationships', ['concept_id_b'], unique=False)
    op.create_index(op.f('ix_concept_relationships_relationship_type'), 'concept_relationships', ['relationship_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concept_relationships_relationship_type'), table_name='concept_relationships')
    op.drop_index(op.f('ix_concept_relationships_concept_id_b'), table_name='concept_relationships')
    op.drop_index(op.f('ix_concept_relationships_concept_id_a'), table_name='concept_relationships')
    op.drop_index('ix_concept_relationships_a_b', table_name='concept_relationships')
    op.drop_table('concept_relationships')
    op.drop_index('ix_concept_names_normalized_name', table_name='concept_names')
    op.drop_index('ix_concept_names_concept_id_name_type', table_name='concept_names')
    op.drop_index(op.f('ix_concept_names_concept_id'), table_name='concept_names')
    op.drop_table('concept_names')
    op.drop_index(op.f('ix_source_records_source_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_concept_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_deduplication_candidates_status'), table_name='deduplication_candidates')
    op.drop_index(op.f('ix_deduplication_candidates_candidate_b'), table_name='deduplication_candidates')
    op.drop_index(op.f('ix_deduplication_candidates_candidate_a'), table_name='deduplication_candidates')
    op.drop_table('deduplication_candidates')
    op.drop_table('sources')
    op.drop_table('id_counters')
    op.drop_index('ix_concepts_domain_category', table_name='concepts')
    op.drop_index(op.f('ix_concepts_domain'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_concept_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_category'), table_name='concepts')
    op.drop_table('concepts')
    # ### end Alembic commands ###
